# https://amralaayassen.medium.com/how-to-create-argocd-applications-automatically-using-applicationset-automation-of-the-gitops-59455eaf4f72#c628
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appName }}-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      directories:
      - path: "*"
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" # HTTPS OR SSH, HTTP UNSUPPORTED
      #repoURL: "https://gitea.swell.casa:3000/ynnckvdv/helm-common.git" # DNS SERVER FIX NEEDED
      revision: HEAD
  template:
    metadata:
      name: '{{`{{ .path.basename }}`}}' # So Helm does not error, need to escape
      namespace: {{ .Values.appName }}-namespace
    spec:
      project: default
      source:
        repoURL: "https://github.com/argoproj/argocd-example-apps.git" # HTTPS OR SSH, HTTP UNSUPPORTED
        #repoURL: "https://gitea.swell.casa:3000/ynnckvdv/helm-common.git" # DNS SERVER FIX NEEDED
        targetRevision: HEAD
        path: '{{`{{ .path }}`}}'
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true