---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName }}-service
    namespace: {{ .Values.appName }}-namespace
spec:
    type: LoadBalancer
    selector:
        app: test
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http